name: lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt

      - name: List installed packages
        run: pip list

      - name: Check Black version
        run: black --version

      - name: Run Black
        run: |
          black . --check --verbose --

  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
          
      - name: List installed packages
        run: pip list
          
      - name: Check Isort version
        run: isort --version
          
      - name: Run Isort
        run: |
          isort . --check --verbose

  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
          
      - name: List installed packages
        run: pip list
          
      - name: Check Flake8 version
        run: flake8 --version
          
      - name: Run Flake8
        run: |
          flake8 . --count --show-source --statistics
